version: '3.8'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  api:
    build:
      context: .
      dockerfile: Dockerfile.development # Use the development Dockerfile
    container_name: api
    restart: unless-stopped
    volumes:
      - .:/app:delegated # Mount current directory to /app in the container
      - /app/node_modules # Mount the node_modules directory as a volume to avoid installation in the container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development # Set environment variable for development
      - PORT=3000 # Set environment variable for port
      - MONGO_URI=mongodb://db:27017/unicon # Set environment variable for MongoDB URI
      - JWT_SECRET=mysecret # Set environment variable for JWT secret
      - JWT_EXPIRATION=1h # Set environment variable for JWT expiration time
    depends_on:
      - db

  admin:
    build:
      context: ../unicon-admin
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=production
    command: npm start
    container_name: admin
    restart: unless-stopped
    volumes:
      - ../unicon-admin:/app:delegated # Mount current directory to /app in the container
      - /app/node_modules # Mount the node_modules directory as a volume to avoid installation in the container
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80" # Expose port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  mongo-data:
