version: '3.8'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://db:27017/unicon
    depends_on:
      - db
  admin:
    build: ../unicon-admin
    environment:
      - NODE_ENV=production
    command: npm start
    ports:
      - "5000:5000"
volumes:
  mongo-data:
