version: '3.8'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  admin:
    build: ../unicon-admin
    environment:
      - NODE_ENV=production
    command: npm start
    container_name: admin
    ports:
      - "5000:5000"

  front:
    build: ../unicon-front
    environment:
      - NODE_ENV=production
    container_name: front
    ports:
      - "3000:3000"
    volumes:
      - ../unicon-front:/app

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80 # Expose port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  api:
    build:
      context: .
      dockerfile: Dockerfile.production # Use the development Dockerfile
    container_name: api
    restart: unless-stopped
    environment:
      - NODE_ENV=production # Set environment variable for production
      - PORT=3000 # Set environment variable for port
      - MONGO_URI=mongodb://db:27017/unicon # Set environment variable for MongoDB URI
      - JWT_SECRET=mysecret # Set environment variable for JWT secret
      - JWT_EXPIRATION=1h # Set environment variable for JWT expiration time
    depends_on:
      - db


volumes:
  mongo-data:
